[package]
name = "allie"
version = "0.1.0"
authors = ["Jimmy 'Kwarf' Bergstr√∂m <thekwarf@gmail.com>"]
license = "MIT"

[dependencies]
clap = "2.21.1"
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
